name: UDUB
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - ipykernel
  - datascience
  - bs4
  - nbformat
  - dash
  - nltk
  - langdetect
  - textblob
  - yfinance
  - nbmerge
  - pdfplumber
  - pytesseract
  - pdf2image
  - statsmodels
